replicaCount: 1

persistence:
  enabled: true
  size: 100Mi
  storageClass: local-path

gelf:
  enabled: true

service:
  type: ClusterIP
  port: 5341

resources:
  requests:
    memory: 256Mi
    cpu: 500m
  limits:
    memory: 256Mi
    cpu: 1000m

env:
  - name: ACCEPT_EULA
    value: "Y"

